pool:
  vmImage: ubuntu-latest

trigger:
  branches:
    include:
      - main

steps:
- script: |
    dotnet restore
    dotnet build --configuration Release
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration Release --output publish_output'
    projects: '*.csproj'
    publishWebProjects: false
    modifyOutputPath: false
    zipAfterPublish: false
- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
    includeRootFolder: false
    archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    artifact: 'drop'
    publishLocation: 'pipeline'
      
- task: AzureFunctionApp@2 # Add this at the end of your file
  inputs:
    connectedServiceNameARM: 'IntuneTLSAuth'
    appType: 'functionAppLinux' # This specifies a Linux-based function app
    isFlexConsumption: true # Uncomment this line if you are deploying to a Flex Consumption app
    appName: 'IntuneTLSAuthDotNet'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    deploymentMethod: 'auto' # 'auto' | 'zipDeploy' | 'runFromPackage'. Required. Deployment method. Default: auto.